# Generated by Django 4.0.1 on 2022-02-01 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_register_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_mentor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='enrolled_students',
        ),
    ]
