services:
  smart_assessment_backend:
    public: true
    image: purnadip2702/smart_assessment_backend:latest
    command: bash -c "gunicorn smartassess.wsgi --reload -b 0.0.0.0:8080"
    build:  .
    ports:
      - "8080:8080" 