# Generated by Django 4.0.1 on 2022-03-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='answer',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
