# Generated by Django 3.2.6 on 2022-02-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_exam_is_evaluated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSubmissionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.BigIntegerField()),
                ('student_id', models.EmailField(max_length=254)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='qstn_marks',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
