# Generated by Django 4.0.1 on 2022-01-28 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('course_details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_mentor', models.ManyToManyField(related_name='course_mentors', to=settings.AUTH_USER_MODEL)),
                ('enrolled_students', models.ManyToManyField(related_name='enrolled_students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
