# Generated by Django 3.2.6 on 2022-01-30 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_register_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('ans_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('answer', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=100, unique=True)),
                ('marks', models.IntegerField()),
                ('level', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default='E', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StandardQnA',
            fields=[
                ('_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('question', models.ManyToManyField(to='assessment.Question')),
                ('std_ans', models.ManyToManyField(to='assessment.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessment.question')),
                ('student_ans', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessment.answer')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('total_questions', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('course', models.ManyToManyField(related_name='course', to='users.Course')),
                ('qna', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessment.qna')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='std_id',
            field=models.ManyToManyField(related_name='answerd_by', to='assessment.Question'),
        ),
    ]
