# Generated by Django 4.0.1 on 2022-02-01 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_register_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=130)),
                ('std_id', models.ManyToManyField(related_name='answerd_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, unique=True)),
                ('marks', models.IntegerField()),
                ('level', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default='E', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StandardQnA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ManyToManyField(to='assessment.Question')),
                ('std_ans', models.ManyToManyField(to='assessment.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.FloatField()),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessment.answer')),
                ('standard_qna', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessment.standardqna')),
            ],
        ),
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessment.question')),
                ('student_ans', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessment.answer')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.TimeField()),
                ('total_questions', models.IntegerField()),
                ('full_marks', models.IntegerField()),
                ('course', models.ManyToManyField(related_name='course', to='users.Course')),
                ('qna', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessment.qna')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks_obtained', models.IntegerField()),
                ('evaluation_date', models.DateTimeField(auto_now_add=True)),
                ('exam_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessment.exam')),
                ('result', models.ManyToManyField(to='assessment.Result')),
            ],
        ),
    ]
