# Generated by Django 3.2.6 on 2022-02-01 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.BigIntegerField()),
                ('question_id', models.BigIntegerField(unique=True)),
                ('answer_id', models.BigIntegerField(unique=True)),
                ('remarks', models.CharField(max_length=130)),
                ('score', models.IntegerField()),
                ('match_percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.BigIntegerField()),
                ('sudent_id', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('is_original', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.BigIntegerField()),
                ('question', models.CharField(max_length=130)),
                ('standard_ans', models.CharField(max_length=130)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=130)),
                ('marks', models.IntegerField()),
                ('course', models.CharField(max_length=130)),
                ('description', models.CharField(max_length=130)),
                ('duration', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.BigIntegerField()),
                ('question_id', models.BigIntegerField(unique=True)),
                ('answer', models.CharField(max_length=130)),
                ('answer_duration', models.TimeField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('answered_by', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
