# Generated by Django 3.2.6 on 2022-01-30 14:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='total_marks',
            new_name='full_marks',
        ),
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('marks_obtained', models.FloatField()),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessment.answer')),
                ('standard_qna', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessment.standardqna')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('total_marks_obtained', models.IntegerField()),
                ('evaluation_date', models.DateTimeField(auto_now_add=True)),
                ('exam_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessment.exam')),
                ('result', models.ManyToManyField(to='assessment.Result')),
            ],
        ),
    ]
