# Generated by Django 3.2.6 on 2022-02-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_answer_question_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evaluation',
        ),
        migrations.AddField(
            model_name='answer',
            name='eval_details',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
        migrations.AddField(
            model_name='answer',
            name='marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='answer',
            name='match_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='answer',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
