# Generated by Django 4.0.1 on 2022-02-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_remove_qna_question_qna_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='qna',
        ),
        migrations.AddField(
            model_name='exam',
            name='qna',
            field=models.ManyToManyField(to='assessment.QnA'),
        ),
    ]
