# Generated by Django 4.0.1 on 2022-02-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_remove_exam_qna_exam_qna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='qna',
        ),
        migrations.AddField(
            model_name='exam',
            name='detailed_information',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_name',
            field=models.CharField(default='NULL', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='standard_qna',
            field=models.ManyToManyField(to='assessment.StandardQnA'),
        ),
    ]
