# Generated by Django 3.2.6 on 2022-02-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_auto_20220207_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
