# Generated by Django 4.0.1 on 2022-02-08 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0004_exam_is_evaluated'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='evaluated_for',
            field=models.ManyToManyField(related_name='evaluated_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
