# Generated by Django 3.2.6 on 2022-02-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_auto_20220218_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_name',
            field=models.CharField(max_length=130, unique=True),
        ),
    ]
