# Generated by Django 4.0.1 on 2022-02-08 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_alter_exam_evaluated_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='evaluated_for',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='is_evaluated',
        ),
    ]
